;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "string-replace-skill")
(def path ".")
(def version "0.4.2")
(def tag "0.4.2")
(def generated-at "2020-11-17T07:14:11Z")
