;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "string-replace-skill")
(def path ".")
(def version "0.4.1")
(def tag "0.4.1")
(def generated-at "2020-11-17T06:31:44Z")
