;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "string-replace-skill")
(def path ".")
(def version "0.4.18")
(def tag "0.4.18")
(def generated-at "2021-02-06T06:00:16Z")
